language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda config --add channels conda-forge

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip scipy pandas matplotlib lmfit cython numba phconvert pytest nbconvert ipykernel ipywidgets pybroom
    - pip install seaborn
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install pathlib ; fi
    - python setup.py build
    - pip install .
    - rm -rf build/

before_script:
    - mkdir notebooks/data
    - cd notebooks/data
    - wget -N http://files.figshare.com/2182604/12d_New_30p_320mW_steer_3.hdf5
    - wget -N http://files.figshare.com/2182601/0023uLRpitc_NTP_20dT_0.5GndCl.hdf5
    - cd ../..
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - python -Wd fretbursts/tests/importtest.py
    - py.test -v
    - cd notebooks
    - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then python ../fretbursts/tests/nbrun.py . ; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python ../fretbursts/tests/nbrun.py --exclude-list dev/exclude-py27.txt . ; fi

sudo: false
