name: fretbursts_env

channels:
- tritemio

dependencies:
- cycler=0.10.0=py35_0
- cython=0.23.4
- freetype=2.5.5=0
- funcsigs=0.4=py35_0
- future=0.15.2=py35_0
- hdf5=1.8.15.1=2
- libpng=1.6.17=0
- llvmlite=0.9.0=py35_0
- matplotlib=1.5.1=np110py35_0
- mkl=11.3.1=0
- mock=1.3.0=py35_0
- nose=1.3.7=py35_0
- numba=0.24.0=np110py35_0
- numexpr=2.4.6=np110py35_1
- numpy=1.10.4=py35_0
- openssl=1.0.2g=0
- pandas=0.18.0=np110py35_0
- pbr=1.3.0=py35_0
- phconvert=0.6.9=py35_0
- pip=8.1.0=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- pytables=3.2.2=np110py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py35_0
- seaborn=0.7.0=py35_0
- setuptools=20.2.2=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - tables==3.2.2
  - lmfit==0.9.2
