name: fretbursts_env

channels:
- tritemio

dependencies:
- cycler=0.10.0
- cython=0.23.4
- freetype=2.5.5
- funcsigs=0.4
- future=0.15.2
- hdf5=1.8.15.1
- libpng=1.6.17
- llvmlite=0.9.0
- lmfit==0.9.2
- matplotlib=1.5.1
- mkl=11.3.1
- mock=1.3.0
- nose=1.3.7
- numba=0.24.0
- numexpr=2.4.6
- numpy=1.10.4
- openssl=1.0.2g
- pandas=0.18.0
- pbr=1.3.0
- phconvert=0.6.9
- pip=8.1.0
- pyparsing=2.0.3
- pyqt=4.11.4
- pytables=3.2.2
- python=3.5.1
- python-dateutil=2.4.2
- pytz=2015.7
- qt=4.8.7
- readline=6.2
- scipy=0.17.0
- seaborn=0.7.0
- setuptools=20.2.2
- sip=4.16.9
- six=1.10.0
- sqlite=3.9.2
- tk=8.5.18
- wheel=0.29.0
- xz=5.0.5
- zlib=1.2.8
- pip:
  - tables==3.2.2
